단순 피쳐 갯수 축소

In [1]:
import mglearn
import pandas as pd
from sklearn.cluster import KMeans

In [2]:
from sklearn.metrics import silhouette_score

In [3]:
df = pd.read_csv('single_variable_data.csv')

In [4]:
df.head()

,risk_depression,risk_drug,risk_iadl,risk_health,risk_age,risk_housing_tenure,risk_unemployed,risk_subj_econ,risk_housing_safety,risk_housing_env,...,risk_smoke,risk_alcohol,risk_suicide,risk_network,risk_infra_gap,risk_aging_rate,risk_health_is_missing,risk_subj_econ_is_missing,risk_housing_env_is_missing,risk_digital_is_missing
0,0.000000,0.1,0.0,0.25,0.514286,0.0,1.0,0.25,0.1250,0.25,...,0.0,1.0,0.0,0.333333,0.621723,0.310723,0,0,0,0
1,0.333333,0.2,0.0,0.75,0.371429,1.0,1.0,0.75,0.6250,0.75,...,0.0,0.0,0.0,0.500000,0.621723,0.310723,0,0,0,0
2,0.133333,0.1,0.0,0.75,0.057143,0.0,0.0,0.75,0.6250,0.50,...,1.0,0.0,0.0,0.333333,0.621723,0.310723,0,0,0,0
3,0.133333,0.0,0.0,0.50,0.571429,0.0,1.0,0.25,0.5000,0.25,...,0.0,0.0,0.0,0.333333,0.621723,0.310723,0,0,0,0
4,0.800000,0.5,0.0,0.75,0.571429,1.0,1.0,0.75,0.5625,0.75,...,0.0,1.0,0.0,0.000000,0.621723,0.310723,0,0,0,0

In [12]:

K_range = range(2,14)
    
for i in range(0,24):
    print(f"{i}번째 열 삭제")
    declined_columns_df = df.drop(df.columns[i], axis=1)
    inertia_kmeans = []
    sil_scores_kmeans = []
    for n_clusters in K_range:
        kmeans = KMeans(n_clusters=n_clusters, random_state=42)
        # n_init: initial centroid 변경횟수   , n_init=10
        # 없이 했다가 추가하니까 실루엣스코어 살짝씩 올랐음
        cluster_labels = kmeans.fit_predict(declined_columns_df)
    
        inertia_kmeans.append(kmeans.inertia_)
        sil_scores_kmeans.append(silhouette_score(declined_columns_df, cluster_labels))
    print("<inertia>")
    print(inertia_kmeans)
    print("<silhouette socre>")
    print(sil_scores_kmeans)

0번째 열 삭제
<inertia>
[4003.0393790403723, 3461.7564488986486, 3231.384329398102, 2974.561808957766, 2737.2342068510297, 2603.194351663569, 2485.031379206977, 2385.3154104189116, 2356.247915477569, 2266.8374526784837, 2216.3847534991037, 2170.7496399415213]
<silhouette socre>
[0.1921896150587018, 0.18610087625925514, 0.1887270605788744, 0.1892574591012742, 0.21393437782581398, 0.19695219553971383, 0.1779340266268694, 0.1898634728108473, 0.17283969344105768, 0.18201765088711638, 0.15665313244346207, 0.15994948407631945]
1번째 열 삭제
<inertia>
[4101.165707325615, 3558.999564115107, 3231.100187895211, 3017.7456880872987, 2946.0649039822792, 2751.915935227866, 2585.66084735686, 2510.3608957197575, 2447.411009930428, 2374.223902760467, 2299.198682529676, 2211.1248137117614]
<silhouette socre>
[0.18864259543333073, 0.18286819434870727, 0.20332807892894972, 0.19524509090004624, 0.18917696883704468, 0.19164243138675, 0.19891340197674406, 0.17840760050285714, 0.16196346978350776, 0.16386170429142935, 0.16771497871735738, 0.17611770117158923]
2번째 열 삭제
<inertia>
[4091.3979765139425, 3759.438245440161, 3354.3734662622205, 3166.4075858644183, 2875.3244362891414, 2681.4382805178425, 2626.1989693110586, 2504.7290869062404, 2441.811751759843, 2367.1832750454037, 2308.8961740637183, 2260.7068827720655]
<silhouette socre>
[0.18764309446937347, 0.16384290411908034, 0.17190547649028504, 0.16658423541590345, 0.19426808386735483, 0.19449523401521923, 0.19648046789870233, 0.2032633382504733, 0.20987844880337594, 0.19339111536449888, 0.17329380639370148, 0.1751432769749616]
3번째 열 삭제
<inertia>
[3992.535995289188, 3487.599587163812, 3272.936020899639, 2955.0947832435504, 2936.235752706412, 2673.7456178517077, 2503.2944417970184, 2427.6605255455265, 2372.0599049934563, 2286.812387364663, 2225.507833775535, 2197.4869414920677]
<silhouette socre>
[0.18998613407809528, 0.18560899995947575, 0.16703411755742584, 0.19948866723137773, 0.16645295829697024, 0.19152629591226691, 0.20544475978815882, 0.184621208069078, 0.17219616265089407, 0.17488304369175434, 0.18264316010095508, 0.16706381406500165]
4번째 열 삭제
<inertia>
[4056.3361946461782, 3530.3390575898075, 3216.258476193738, 2949.1799332028386, 2856.802898123174, 2780.314356463196, 2558.5348077752387, 2467.1111507162786, 2403.711906507266, 2341.4946997179027, 2267.2939040803612, 2201.3487678124666]
<silhouette socre>
[0.1891620614723898, 0.18267513252637477, 0.20243965069656122, 0.21104115962378303, 0.1765508438027298, 0.1804984568679771, 0.1788837049225619, 0.18623461177312015, 0.1670698952484619, 0.17080591153786617, 0.174580202044885, 0.17636539914941105]
5번째 열 삭제
<inertia>
[3783.0019666508424, 3240.6492902441396, 3015.581881588767, 2814.3515526884426, 2540.728645723764, 2469.9153997892954, 2328.6621257104143, 2261.333267273238, 2219.278357235412, 2143.091805539564, 2076.1794114662293, 2051.725795057979]
<silhouette socre>
[0.20088456616318856, 0.19276702099918755, 0.1819556307197083, 0.18141999508995096, 0.20882638827844674, 0.17987455937923083, 0.20324938195394715, 0.1764662627712583, 0.16080646499301868, 0.1652333954113127, 0.17310977529576263, 0.16804813443651148]
6번째 열 삭제
<inertia>
[3822.9388982943965, 3073.6669819062136, 2889.5311336254213, 2557.136747229583, 2442.2313503265773, 2383.924124635725, 2292.3891219618845, 2202.115174312939, 2102.7698094515313, 2054.878476062092, 2026.436433661603, 1993.5903261730814]
<silhouette socre>
[0.20707269213972732, 0.1993747346050802, 0.1740091244131451, 0.20333516538587226, 0.16085490264912544, 0.1454413670747852, 0.1248510653209848, 0.12676522868833567, 0.14058618736803213, 0.1347008181740796, 0.12419554637737103, 0.12305099056638964]
7번째 열 삭제
<inertia>
[4043.859870109514, 3743.7295061895898, 3370.8211104149996, 3020.286073154887, 2785.095575618584, 2704.7756663701825, 2543.343323304948, 2480.4919507008863, 2428.9599955125536, 2347.2251549618763, 2286.054769244386, 2220.938842451956]
<silhouette socre>
[0.1911576352271151, 0.18754615631808838, 0.17374578830592316, 0.2088881685689293, 0.2115966340629559, 0.1785203245672296, 0.1827220911478867, 0.16108147779510504, 0.14146401434376937, 0.1436313989387586, 0.14979145621547016, 0.15007805204067212]
8번째 열 삭제
<inertia>
[4036.9026290866664, 3494.3333859140444, 3258.377442217339, 3071.3279511019873, 2844.0560192271114, 2583.7051300204457, 2601.0890298484856, 2457.5248121217323, 2366.961065664421, 2332.4500911976406, 2261.8233634525227, 2160.2563129304394]
<silhouette socre>
[0.19202615015713823, 0.18636860596824406, 0.1767629456725077, 0.1712543860938096, 0.1755699903458567, 0.20357805978871663, 0.15059272910688665, 0.16398578103994477, 0.17160420200015503, 0.16464559350022254, 0.1662915281615122, 0.17556329983807023]
9번째 열 삭제
<inertia>
[4086.540465202589, 3544.3273817898566, 3328.7971653635245, 3116.9119322939378, 2987.9788804902028, 2830.603171765791, 2579.4394519778234, 2478.5440227369854, 2420.1474348040197, 2330.3944893055605, 2285.941969526373, 2207.9036930648995]
<silhouette socre>
[0.18952853749550605, 0.1837076150688018, 0.16448799423972785, 0.16295867575709932, 0.14229231126004263, 0.14868771655216986, 0.18182277418051582, 0.18361751739502571, 0.18436080120143938, 0.19360872264525322, 0.17072227574941598, 0.1816052527739596]
10번째 열 삭제
<inertia>
[4003.8720079272116, 3700.3045626918324, 3340.3067131917933, 2993.9467469783185, 2740.4843817602946, 2686.227568965889, 2522.2065931113984, 2429.171378562326, 2365.2662735200474, 2317.716559164789, 2239.425096285227, 2161.278116414407]
<silhouette socre>
[0.18973653935388352, 0.18372766688288075, 0.16361048809137962, 0.20182436065170334, 0.21192076643100138, 0.19224205145142173, 0.18066858050434134, 0.1896036068987635, 0.1705963938522708, 0.17363811432320106, 0.17652660813656315, 0.18720889016056572]
11번째 열 삭제
<inertia>
[3809.8684309327273, 3267.862312774866, 2998.094654793458, 2684.2863923821883, 2515.043636344161, 2469.5083633950103, 2332.231316268705, 2233.230171565456, 2177.9015856399187, 2130.062019725461, 2078.567532713361, 2034.7085731214697]
<silhouette socre>
[0.19999456033410146, 0.1951710858067298, 0.194956881528165, 0.22805567774153274, 0.22699788514837477, 0.2120668626245594, 0.2019745301674156, 0.20873857778460317, 0.21471992645190152, 0.2017132729111358, 0.17635603571860764, 0.1709990198838681]
12번째 열 삭제
<inertia>
[3398.672503035891, 3065.040443023664, 2876.996153720035, 2677.0060523329357, 2567.503320535001, 2444.600689878145, 2239.735575385765, 2158.206718530094, 2101.480494957429, 2057.1004506718987, 2015.5060501367227, 1939.651280663949]
<silhouette socre>
[0.21539219795930262, 0.19044183353926294, 0.18503908892285012, 0.2080068101090733, 0.17559414356978442, 0.1447588464813233, 0.15115170249211493, 0.15608473834113873, 0.15526530335360833, 0.1478123847013438, 0.1376520075322514, 0.1414646999797481]
13번째 열 삭제
<inertia>
[4085.27729284667, 3543.6375342229185, 3313.303287126941, 2949.3599733788487, 2855.641870991253, 2727.5310163591344, 2583.7452525619583, 2520.4152696410733, 2448.4604611611835, 2353.888558494376, 2289.1665502750193, 2254.818283182969]
<silhouette socre>
[0.18940675320053196, 0.18362319464811466, 0.18600910119802327, 0.21268861245205212, 0.21284276645903158, 0.20958264196948054, 0.19913940395537907, 0.19938660012480122, 0.17632687488087864, 0.1850750514243555, 0.1911345053224238, 0.17998124958338624]
14번째 열 삭제
<inertia>
[3946.8758511513765, 3613.9734834293786, 3209.1819474101403, 2901.7849814104275, 2701.1861330367406, 2535.080297112522, 2534.7475440877793, 2475.570772485877, 2367.5645835860837, 2304.2142974376634, 2279.0670532076174, 2137.9011536084595]
<silhouette socre>
[0.1925779224068474, 0.17047086393636113, 0.1763249958971631, 0.20105926732918294, 0.20227433764514963, 0.20478568828954763, 0.1797033100802747, 0.1607463366714747, 0.1620387380001704, 0.1691920805614267, 0.17052972493548552, 0.1848922110596941]
15번째 열 삭제
<inertia>
[3759.7979629692995, 3272.2204788547947, 2894.565891575874, 2680.4286998632824, 2605.5892800397755, 2453.793588190687, 2329.8838192800204, 2232.8324663705525, 2172.855170973098, 2107.526063490146, 2033.1310086130504, 1996.6376291791094]
<silhouette socre>
[0.19918893883914926, 0.18242183690656408, 0.21866437717376888, 0.21495390089084024, 0.1776034526540897, 0.19065365736586337, 0.19084686797185876, 0.20114674518910097, 0.1733250248046334, 0.15479128909937134, 0.15922180728052046, 0.14647060491905498]
16번째 열 삭제
<inertia>
[4115.721226732236, 3573.1275718997836, 3337.2466832395644, 3099.4422134779406, 2829.198514081192, 2685.5456760405336, 2596.9653643379843, 2530.704398209932, 2447.9766779630136, 2382.0387573850617, 2297.232388897086, 2206.33091174576]
<silhouette socre>
[0.18775004177673632, 0.1811174640219532, 0.1712799722538327, 0.1719310566290895, 0.1939999797689574, 0.1986021057905675, 0.20309747973873474, 0.17658786046890737, 0.166678746992294, 0.14655439240532758, 0.17011639734481496, 0.18004493234978544]
17번째 열 삭제
<inertia>
[3867.983332822304, 3367.347269740449, 3037.942829361688, 2883.8522431287824, 2608.291169604164, 2558.329043967994, 2444.190739323627, 2351.3755590886444, 2252.865283175947, 2222.585186161984, 2163.944319354801, 2111.6135780729014]
<silhouette socre>
[0.1962475319444318, 0.1903373110646194, 0.21290521378189528, 0.21533829591279752, 0.2201679542175987, 0.19813900097978138, 0.17235349616560947, 0.18104550837528305, 0.19001291851932342, 0.18099050933054306, 0.16343071893635483, 0.16949100862912755]
18번째 열 삭제
<inertia>
[3988.693963844745, 3601.159804813183, 3161.5799311885303, 2948.274616641236, 2875.253914839027, 2711.9021093032716, 2565.523293516333, 2501.479166094913, 2352.3959333615094, 2321.0416106222497, 2299.576939895127, 2242.2842058480196]
<silhouette socre>
[0.19165909936140751, 0.1684145402281059, 0.20801927765658976, 0.20087354269364802, 0.19423919721505334, 0.19969970840328424, 0.18516564151821394, 0.1857578937456291, 0.19333592007810785, 0.1756469466503478, 0.16836011931943623, 0.15036944446450243]
19번째 열 삭제
<inertia>
[4046.165226942473, 3745.738006205715, 3275.170680148325, 3017.3187840410856, 2865.5412532880428, 2830.1969970671294, 2674.4875926784807, 2490.0209605146347, 2430.9473363311986, 2346.8408874074753, 2301.0929038655663, 2193.3354063966744]
<silhouette socre>
[0.19010839061376802, 0.18613525026231023, 0.18795528417893437, 0.187940716032917, 0.17289179741031754, 0.16326301018520487, 0.1401324553639845, 0.15294897622320885, 0.14125645002299111, 0.14662246517156752, 0.14877822398566012, 0.15607873161296282]
20번째 열 삭제
<inertia>
[4121.900560613927, 3729.887888739083, 3289.510762091518, 3110.1717346225732, 2878.8267659293706, 2815.2586400938653, 2727.008888546772, 2611.72650928753, 2580.353992465498, 2507.8344446854635, 2448.704918021312, 2383.7466999379935]
<silhouette socre>
[0.186558712680435, 0.16297088576770577, 0.19971030019155384, 0.1955860609360951, 0.20724448205175758, 0.20228014986354406, 0.1836389700607195, 0.16772750601010622, 0.14959627987146182, 0.15484730131107582, 0.13745269604345584, 0.14148953910067674]
21번째 열 삭제
<inertia>
[4121.900560613927, 3729.887888739083, 3289.510762091518, 3110.1717346225732, 2878.8267659293706, 2815.2586400938653, 2727.008888546772, 2611.72650928753, 2580.353992465498, 2507.8344446854635, 2448.704918021312, 2383.7466999379935]
<silhouette socre>
[0.186558712680435, 0.16297088576770577, 0.19971030019155384, 0.1955860609360951, 0.20724448205175758, 0.20228014986354406, 0.1836389700607195, 0.16772750601010622, 0.14959627987146182, 0.15484730131107582, 0.13745269604345584, 0.14148953910067674]
22번째 열 삭제
<inertia>
[4121.900560613927, 3729.887888739083, 3289.510762091518, 3110.1717346225732, 2878.8267659293706, 2815.2586400938653, 2727.008888546772, 2611.72650928753, 2580.353992465498, 2507.8344446854635, 2448.704918021312, 2383.7466999379935]
<silhouette socre>
[0.186558712680435, 0.16297088576770577, 0.19971030019155384, 0.1955860609360951, 0.20724448205175758, 0.20228014986354406, 0.1836389700607195, 0.16772750601010622, 0.14959627987146182, 0.15484730131107582, 0.13745269604345584, 0.14148953910067674]
23번째 열 삭제
<inertia>
[4143.596937842221, 3751.4430986924253, 3311.0849556399035, 3096.794063420938, 2896.1343201404966, 2811.7502342929056, 2685.2013309877325, 2584.4675730808804, 2509.9738685334846, 2452.1467560362307, 2366.481599522372, 2333.939671810294]
<silhouette socre>
[0.18620310530851006, 0.16265879951765322, 0.1989771204905529, 0.191751088099379, 0.18951117050470517, 0.1663146587958891, 0.16693881110685393, 0.17151263715801882, 0.17431838677649533, 0.17506359422646064, 0.17852737786274078, 0.17151725051643463]

In [15]:
scores = pd.DataFrame(columns=range(0,24))

In [16]:
scores

Empty DataFrame
Columns: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]
Index: []

[0 rows x 24 columns]

In [17]:
K_range = range(2,14)

#열 1개 삭제

for i in range(0,24):
    print(f"{i}번째 열 삭제")
    declined_columns_df = df.drop(df.columns[i], axis=1)
    
    highest_sil=0
    for n_clusters in K_range:
        kmeans = KMeans(n_clusters=n_clusters, random_state=42)
        # n_init: initial centroid 변경횟수   , n_init=10
        # 없이 했다가 추가하니까 실루엣스코어 살짝씩 올랐음
        cluster_labels = kmeans.fit_predict(declined_columns_df)
        
        if (silhouette_score(declined_columns_df, cluster_labels) > highest_sil):
            highest_sil = silhouette_score(declined_columns_df, cluster_labels)
            
    print(f"highest_sil: {highest_sil}")

0번째 열 삭제
column 0 is dismissed
highest_sil: 0.21393437782581398
highest_inertia: 4003.0393790403723
1번째 열 삭제
column 1 is dismissed
highest_sil: 0.20332807892894972
highest_inertia: 4101.165707325615
2번째 열 삭제
column 2 is dismissed
highest_sil: 0.20987844880337594
highest_inertia: 4091.3979765139425
3번째 열 삭제
column 3 is dismissed
highest_sil: 0.20544475978815882
highest_inertia: 3992.535995289188
4번째 열 삭제
column 4 is dismissed
highest_sil: 0.21104115962378303
highest_inertia: 4056.3361946461782
5번째 열 삭제
column 5 is dismissed
highest_sil: 0.20882638827844674
highest_inertia: 3783.0019666508433
6번째 열 삭제
column 6 is dismissed
highest_sil: 0.20707269213972732
highest_inertia: 3822.9388982943956
7번째 열 삭제
column 7 is dismissed
highest_sil: 0.2115966340629559
highest_inertia: 4043.859870109514
8번째 열 삭제
column 8 is dismissed
highest_sil: 0.20357805978871663
highest_inertia: 4036.9026290866664
9번째 열 삭제
column 9 is dismissed
highest_sil: 0.19360872264525322
highest_inertia: 4086.540465202589
10번째 열 삭제
column 10 is dismissed
highest_sil: 0.21192076643100138
highest_inertia: 4003.8720079272116
11번째 열 삭제
column 11 is dismissed
highest_sil: 0.22805567774153274
highest_inertia: 3809.8684309327273
12번째 열 삭제
column 12 is dismissed
highest_sil: 0.21539219795930262
highest_inertia: 3398.672503035891
13번째 열 삭제
column 13 is dismissed
highest_sil: 0.21284276645903158
highest_inertia: 4085.27729284667
14번째 열 삭제
column 14 is dismissed
highest_sil: 0.20478568828954763
highest_inertia: 3946.8758511513765
15번째 열 삭제
column 15 is dismissed
highest_sil: 0.21866437717376888
highest_inertia: 3759.7979629692995
16번째 열 삭제
column 16 is dismissed
highest_sil: 0.20309747973873474
highest_inertia: 4115.721226732236
17번째 열 삭제
column 17 is dismissed
highest_sil: 0.2201679542175987
highest_inertia: 3867.983332822304
18번째 열 삭제
column 18 is dismissed
highest_sil: 0.20801927765658976
highest_inertia: 3988.693963844745
19번째 열 삭제
column 19 is dismissed
highest_sil: 0.19010839061376802
highest_inertia: 4046.165226942473
20번째 열 삭제
column 20 is dismissed
highest_sil: 0.20724448205175758
highest_inertia: 4121.900560613927
21번째 열 삭제
column 21 is dismissed
highest_sil: 0.20724448205175758
highest_inertia: 4121.900560613927
22번째 열 삭제
column 22 is dismissed
highest_sil: 0.20724448205175758
highest_inertia: 4121.900560613927
23번째 열 삭제
column 23 is dismissed
highest_sil: 0.1989771204905529
highest_inertia: 4143.596937842221

In [19]:
K_range = range(2,14)

#열 2개 삭제

for j in range(0,24):
    range_without_j = [x for x in range(24) if x != j]
    for i in range_without_j:
        print(f"{j}, {i}번째 열 삭제")
        declined_columns_df = df.drop([df.columns[i], df.columns[j]], axis=1)

        highest_sil=0
        
        for n_clusters in K_range:
            kmeans = KMeans(n_clusters=n_clusters, random_state=42)
       
            cluster_labels = kmeans.fit_predict(declined_columns_df)
        
            if (silhouette_score(declined_columns_df, cluster_labels) > highest_sil):
                highest_sil = silhouette_score(declined_columns_df, cluster_labels)
            
        print(f"highest_sil: {highest_sil}")

0, 1번째 열 삭제
highest_sil: 0.20862313389015918
0, 2번째 열 삭제
highest_sil: 0.22063487379335478
0, 3번째 열 삭제
highest_sil: 0.246120095367323
0, 4번째 열 삭제
highest_sil: 0.19558490012493432
0, 5번째 열 삭제
highest_sil: 0.22972450398567357
0, 6번째 열 삭제
highest_sil: 0.2366308101671336
0, 7번째 열 삭제
highest_sil: 0.22603874568362103
0, 8번째 열 삭제
highest_sil: 0.21441272564892241
0, 9번째 열 삭제
highest_sil: 0.2212308490087336
0, 10번째 열 삭제
highest_sil: 0.2094383476894169
0, 11번째 열 삭제
highest_sil: 0.24031771643257974
0, 12번째 열 삭제
highest_sil: 0.23388210803667886
0, 13번째 열 삭제
highest_sil: 0.2289426386074616
0, 14번째 열 삭제
highest_sil: 0.21824733872447802
0, 15번째 열 삭제
highest_sil: 0.24219422205773902
0, 16번째 열 삭제
highest_sil: 0.21907766178898377
0, 17번째 열 삭제
highest_sil: 0.23356255340938223
0, 18번째 열 삭제
highest_sil: 0.21130525469559525
0, 19번째 열 삭제
highest_sil: 0.2164981764630592
0, 20번째 열 삭제
highest_sil: 0.2150728171566271
0, 21번째 열 삭제
highest_sil: 0.2150728171566271
0, 22번째 열 삭제
highest_sil: 0.2150728171566271
0, 23번째 열 삭제
highest_sil: 0.20522093144419096
1, 0번째 열 삭제
highest_sil: 0.20862313389015918
1, 2번째 열 삭제
highest_sil: 0.21418127273379892
1, 3번째 열 삭제
highest_sil: 0.21168201413115345
1, 4번째 열 삭제
highest_sil: 0.18863055672006798
1, 5번째 열 삭제
highest_sil: 0.20324475752271648
1, 6번째 열 삭제
highest_sil: 0.22036949815792098
1, 7번째 열 삭제
highest_sil: 0.21687677129069982
1, 8번째 열 삭제
highest_sil: 0.22155414556188774
1, 9번째 열 삭제
highest_sil: 0.20513540181227627
1, 10번째 열 삭제
highest_sil: 0.2194575325661719
1, 11번째 열 삭제
highest_sil: 0.23343460625699422
1, 12번째 열 삭제
highest_sil: 0.22803011037723056
1, 13번째 열 삭제
highest_sil: 0.2076947455177156
1, 14번째 열 삭제
highest_sil: 0.21158180645672187
1, 15번째 열 삭제
highest_sil: 0.2350001555608316
1, 16번째 열 삭제
highest_sil: 0.21522814995943368
1, 17번째 열 삭제
highest_sil: 0.22715370547378305
1, 18번째 열 삭제
highest_sil: 0.2225727298192605
1, 19번째 열 삭제
highest_sil: 0.21059294520877705
1, 20번째 열 삭제
highest_sil: 0.2121780567469041
1, 21번째 열 삭제
highest_sil: 0.2121780567469041
1, 22번째 열 삭제
highest_sil: 0.2121780567469041
1, 23번째 열 삭제
highest_sil: 0.2117377764812766
2, 0번째 열 삭제
highest_sil: 0.22063487379335478
2, 1번째 열 삭제
highest_sil: 0.21418127273379892
2, 3번째 열 삭제
highest_sil: 0.2175070947811453
2, 4번째 열 삭제
highest_sil: 0.19550782042706327
2, 5번째 열 삭제
highest_sil: 0.2013974793063438
2, 6번째 열 삭제
highest_sil: 0.21795470529459643
2, 7번째 열 삭제
highest_sil: 0.20387186445149116
2, 8번째 열 삭제
highest_sil: 0.21106423927174991
2, 9번째 열 삭제
highest_sil: 0.20713975763855452
2, 10번째 열 삭제
highest_sil: 0.21699379577281286
2, 11번째 열 삭제
highest_sil: 0.23577576780160278
2, 12번째 열 삭제
highest_sil: 0.2256345467000451
2, 13번째 열 삭제
highest_sil: 0.22049537327905253
2, 14번째 열 삭제
highest_sil: 0.2135809411758533
2, 15번째 열 삭제
highest_sil: 0.23207361215771768
2, 16번째 열 삭제
highest_sil: 0.2043429121954855
2, 17번째 열 삭제
highest_sil: 0.1999640185848522
2, 18번째 열 삭제
highest_sil: 0.1997021816684386
2, 19번째 열 삭제
highest_sil: 0.2147826014729463
2, 20번째 열 삭제
highest_sil: 0.20981080281980338
2, 21번째 열 삭제
highest_sil: 0.20981080281980338
2, 22번째 열 삭제
highest_sil: 0.20981080281980338
2, 23번째 열 삭제
highest_sil: 0.20934937637523077
3, 0번째 열 삭제
highest_sil: 0.246120095367323
3, 1번째 열 삭제
highest_sil: 0.21168201413115345
3, 2번째 열 삭제
highest_sil: 0.2175070947811453
3, 4번째 열 삭제
highest_sil: 0.21117509140611135
3, 5번째 열 삭제
highest_sil: 0.2044153212036938
3, 6번째 열 삭제
highest_sil: 0.2245265054402364
3, 7번째 열 삭제
highest_sil: 0.1955008660248502
3, 8번째 열 삭제
highest_sil: 0.22562501425643233
3, 9번째 열 삭제
highest_sil: 0.22146794711690743
3, 10번째 열 삭제
highest_sil: 0.21605833989397696
3, 11번째 열 삭제
highest_sil: 0.23818669420938127
3, 12번째 열 삭제
highest_sil: 0.22347745983119044
3, 13번째 열 삭제
highest_sil: 0.223204069088803
3, 14번째 열 삭제
highest_sil: 0.21331644253899285
3, 15번째 열 삭제
highest_sil: 0.22820397568806286
3, 16번째 열 삭제
highest_sil: 0.20105856728341373
3, 17번째 열 삭제
highest_sil: 0.2201576235242585
3, 18번째 열 삭제
highest_sil: 0.22782740874660148
3, 19번째 열 삭제
highest_sil: 0.21281380347900908
3, 20번째 열 삭제
highest_sil: 0.20768101370751751
3, 21번째 열 삭제
highest_sil: 0.20768101370751751
3, 22번째 열 삭제
highest_sil: 0.20768101370751751
3, 23번째 열 삭제
highest_sil: 0.2058332889485323
4, 0번째 열 삭제
highest_sil: 0.19558490012493432
4, 1번째 열 삭제
highest_sil: 0.18863055672006798
4, 2번째 열 삭제
highest_sil: 0.19550782042706327
4, 3번째 열 삭제
highest_sil: 0.21117509140611135
4, 5번째 열 삭제
highest_sil: 0.21092606946471554
4, 6번째 열 삭제
highest_sil: 0.21954528412380245
4, 7번째 열 삭제
highest_sil: 0.2107037879969
4, 8번째 열 삭제
highest_sil: 0.21166399061063043
4, 9번째 열 삭제
highest_sil: 0.2011540941578861
4, 10번째 열 삭제
highest_sil: 0.19539103945828928
4, 11번째 열 삭제
highest_sil: 0.23287459362188895
4, 12번째 열 삭제
highest_sil: 0.22965217639145077
4, 13번째 열 삭제
highest_sil: 0.21057021182954253
4, 14번째 열 삭제
highest_sil: 0.22070502995856014
4, 15번째 열 삭제
highest_sil: 0.2226330805496583
4, 16번째 열 삭제
highest_sil: 0.21431502018315987
4, 17번째 열 삭제
highest_sil: 0.23203811073635572
4, 18번째 열 삭제
highest_sil: 0.22029588916091494
4, 19번째 열 삭제
highest_sil: 0.20966784766398408
4, 20번째 열 삭제
highest_sil: 0.21155746154631397
4, 21번째 열 삭제
highest_sil: 0.21155746154631397
4, 22번째 열 삭제
highest_sil: 0.21155746154631397
4, 23번째 열 삭제
highest_sil: 0.20246260071031977
5, 0번째 열 삭제
highest_sil: 0.22972450398567357
5, 1번째 열 삭제
highest_sil: 0.20324475752271648
5, 2번째 열 삭제
highest_sil: 0.2013974793063438
5, 3번째 열 삭제
highest_sil: 0.2044153212036938
5, 4번째 열 삭제
highest_sil: 0.21092606946471554
5, 6번째 열 삭제
highest_sil: 0.23394903108504064
5, 7번째 열 삭제
highest_sil: 0.22762126714305245
5, 8번째 열 삭제
highest_sil: 0.2084528668749997
5, 9번째 열 삭제
highest_sil: 0.22461506700976885
5, 10번째 열 삭제
highest_sil: 0.21599681236601218
5, 11번째 열 삭제
highest_sil: 0.24117549217467923
5, 12번째 열 삭제
highest_sil: 0.23555770775684404
5, 13번째 열 삭제
highest_sil: 0.21180519553958352
5, 14번째 열 삭제
highest_sil: 0.22797166535650043
5, 15번째 열 삭제
highest_sil: 0.24126095621024
5, 16번째 열 삭제
highest_sil: 0.20194674570026758
5, 17번째 열 삭제
highest_sil: 0.2347848210521577
5, 18번째 열 삭제
highest_sil: 0.21704069258728126
5, 19번째 열 삭제
highest_sil: 0.22432407727000137
5, 20번째 열 삭제
highest_sil: 0.20565094433275877
5, 21번째 열 삭제
highest_sil: 0.20565094433275877
5, 22번째 열 삭제
highest_sil: 0.20565094433275877
5, 23번째 열 삭제
highest_sil: 0.20884206643978992
6, 0번째 열 삭제
highest_sil: 0.2366308101671336
6, 1번째 열 삭제
highest_sil: 0.22036949815792098
6, 2번째 열 삭제
highest_sil: 0.21795470529459643
6, 3번째 열 삭제
highest_sil: 0.2245265054402364
6, 4번째 열 삭제
highest_sil: 0.21954528412380245
6, 5번째 열 삭제
highest_sil: 0.23394903108504064
6, 7번째 열 삭제
highest_sil: 0.2233152135804464
6, 8번째 열 삭제
highest_sil: 0.2359978920895829
6, 9번째 열 삭제
highest_sil: 0.22133301823016285
6, 10번째 열 삭제
highest_sil: 0.23293634052608575
6, 11번째 열 삭제
highest_sil: 0.24755263421900625
6, 12번째 열 삭제
highest_sil: 0.18681143522594443
6, 13번째 열 삭제
highest_sil: 0.22206830177693146
6, 14번째 열 삭제
highest_sil: 0.23653519570748846
6, 15번째 열 삭제
highest_sil: 0.23734205171983017
6, 16번째 열 삭제
highest_sil: 0.22946026144236398
6, 17번째 열 삭제
highest_sil: 0.2445675740793973
6, 18번째 열 삭제
highest_sil: 0.23485281510922393
6, 19번째 열 삭제
highest_sil: 0.2332829590541938
6, 20번째 열 삭제
highest_sil: 0.2266115564900072
6, 21번째 열 삭제
highest_sil: 0.2266115564900072
6, 22번째 열 삭제
highest_sil: 0.2266115564900072
6, 23번째 열 삭제
highest_sil: 0.22629054986401012
7, 0번째 열 삭제
highest_sil: 0.22603874568362103
7, 1번째 열 삭제
highest_sil: 0.21687677129069982
7, 2번째 열 삭제
highest_sil: 0.20387186445149116
7, 3번째 열 삭제
highest_sil: 0.1955008660248502
7, 4번째 열 삭제
highest_sil: 0.2107037879969
7, 5번째 열 삭제
highest_sil: 0.22762126714305245
7, 6번째 열 삭제
highest_sil: 0.2233152135804464
7, 8번째 열 삭제
highest_sil: 0.22657499463819875
7, 9번째 열 삭제
highest_sil: 0.2208442920760051
7, 10번째 열 삭제
highest_sil: 0.19526756538347176
7, 11번째 열 삭제
highest_sil: 0.2462575044348931
7, 12번째 열 삭제
highest_sil: 0.2231185604738954
7, 13번째 열 삭제
highest_sil: 0.2277917414939627
7, 14번째 열 삭제
highest_sil: 0.2117161877847871
7, 15번째 열 삭제
highest_sil: 0.22802952036444774
7, 16번째 열 삭제
highest_sil: 0.2053250553498559
7, 17번째 열 삭제
highest_sil: 0.231221704330906
7, 18번째 열 삭제
highest_sil: 0.22568784864766112
7, 19번째 열 삭제
highest_sil: 0.22378741475661054
7, 20번째 열 삭제
highest_sil: 0.20255445870710334
7, 21번째 열 삭제
highest_sil: 0.20255445870710334
7, 22번째 열 삭제
highest_sil: 0.20255445870710334
7, 23번째 열 삭제
highest_sil: 0.21240867671024147
8, 0번째 열 삭제
highest_sil: 0.21441272564892241
8, 1번째 열 삭제
highest_sil: 0.22155414556188774
8, 2번째 열 삭제
highest_sil: 0.21106423927174991
8, 3번째 열 삭제
highest_sil: 0.22562501425643233
8, 4번째 열 삭제
highest_sil: 0.21166399061063043
8, 5번째 열 삭제
highest_sil: 0.2084528668749997
8, 6번째 열 삭제
highest_sil: 0.2359978920895829
8, 7번째 열 삭제
highest_sil: 0.22657499463819875
8, 9번째 열 삭제
highest_sil: 0.2160458626855992
8, 10번째 열 삭제
highest_sil: 0.21551966290258895
8, 11번째 열 삭제
highest_sil: 0.23941514787466645
8, 12번째 열 삭제
highest_sil: 0.22422423886471798
8, 13번째 열 삭제
highest_sil: 0.2232935678422237
8, 14번째 열 삭제
highest_sil: 0.2147481673167855
8, 15번째 열 삭제
highest_sil: 0.22701426427552432
8, 16번째 열 삭제
highest_sil: 0.21964855480617476
8, 17번째 열 삭제
highest_sil: 0.23202110015393002
8, 18번째 열 삭제
highest_sil: 0.20549382935097496
8, 19번째 열 삭제
highest_sil: 0.22538061820880098
8, 20번째 열 삭제
highest_sil: 0.20707928617328397
8, 21번째 열 삭제
highest_sil: 0.20707928617328397
8, 22번째 열 삭제
highest_sil: 0.20707928617328397
8, 23번째 열 삭제
highest_sil: 0.20357409452579764
9, 0번째 열 삭제
highest_sil: 0.2212308490087336
9, 1번째 열 삭제
highest_sil: 0.20513540181227627
9, 2번째 열 삭제
highest_sil: 0.20713975763855452
9, 3번째 열 삭제
highest_sil: 0.22146794711690743
9, 4번째 열 삭제
highest_sil: 0.2011540941578861
9, 5번째 열 삭제
highest_sil: 0.22461506700976885
9, 6번째 열 삭제
highest_sil: 0.22133301823016285
9, 7번째 열 삭제
highest_sil: 0.2208442920760051
9, 8번째 열 삭제
highest_sil: 0.2160458626855992
9, 10번째 열 삭제
highest_sil: 0.2240262260702935
9, 11번째 열 삭제
highest_sil: 0.2400453372178835
9, 12번째 열 삭제
highest_sil: 0.22872657227043303
9, 13번째 열 삭제
highest_sil: 0.20474005606102666
9, 14번째 열 삭제
highest_sil: 0.21171986689988964
9, 15번째 열 삭제
highest_sil: 0.2306533123669225
9, 16번째 열 삭제
highest_sil: 0.2027575391919102
9, 17번째 열 삭제
highest_sil: 0.23423212162484416
9, 18번째 열 삭제
highest_sil: 0.21274255452758403
9, 19번째 열 삭제
highest_sil: 0.2078278439821321
9, 20번째 열 삭제
highest_sil: 0.21136788762237588
9, 21번째 열 삭제
highest_sil: 0.21136788762237588
9, 22번째 열 삭제
highest_sil: 0.21136788762237588
9, 23번째 열 삭제
highest_sil: 0.21042296973037192
10, 0번째 열 삭제
highest_sil: 0.2094383476894169
10, 1번째 열 삭제
highest_sil: 0.2194575325661719
10, 2번째 열 삭제
highest_sil: 0.21699379577281286
10, 3번째 열 삭제
highest_sil: 0.21605833989397696
10, 4번째 열 삭제
highest_sil: 0.19539103945828928
10, 5번째 열 삭제
highest_sil: 0.21599681236601218
10, 6번째 열 삭제
highest_sil: 0.23293634052608575
10, 7번째 열 삭제
highest_sil: 0.19526756538347176
10, 8번째 열 삭제
highest_sil: 0.21551966290258895
10, 9번째 열 삭제
highest_sil: 0.2240262260702935
10, 11번째 열 삭제
highest_sil: 0.23722603556790056
10, 12번째 열 삭제
highest_sil: 0.22405720664890777
10, 13번째 열 삭제
highest_sil: 0.22658388744777275
10, 14번째 열 삭제
highest_sil: 0.21507908212377894
10, 15번째 열 삭제
highest_sil: 0.21435547823897647
10, 16번째 열 삭제
highest_sil: 0.19371345710029575
10, 17번째 열 삭제
highest_sil: 0.23727574436578183
10, 18번째 열 삭제
highest_sil: 0.205918552143757
10, 19번째 열 삭제
highest_sil: 0.2334403137449138
10, 20번째 열 삭제
highest_sil: 0.21625474458549793
10, 21번째 열 삭제
highest_sil: 0.21625474458549793
10, 22번째 열 삭제
highest_sil: 0.21625474458549793
10, 23번째 열 삭제
highest_sil: 0.20645346426996183
11, 0번째 열 삭제
highest_sil: 0.24031771643257974
11, 1번째 열 삭제
highest_sil: 0.23343460625699422
11, 2번째 열 삭제
highest_sil: 0.23577576780160278
11, 3번째 열 삭제
highest_sil: 0.23818669420938127
11, 4번째 열 삭제
highest_sil: 0.23287459362188895
11, 5번째 열 삭제
highest_sil: 0.24117549217467923
11, 6번째 열 삭제
highest_sil: 0.24755263421900625
11, 7번째 열 삭제
highest_sil: 0.2462575044348931
11, 8번째 열 삭제
highest_sil: 0.23941514787466645
11, 9번째 열 삭제
highest_sil: 0.2400453372178835
11, 10번째 열 삭제
highest_sil: 0.23722603556790056
11, 12번째 열 삭제
highest_sil: 0.24568218381171916
11, 13번째 열 삭제
highest_sil: 0.23383059677683263
11, 14번째 열 삭제
highest_sil: 0.23811463116266737
11, 15번째 열 삭제
highest_sil: 0.25490704358401156
11, 16번째 열 삭제
highest_sil: 0.23666840874608136
11, 17번째 열 삭제
highest_sil: 0.2545391714282018
11, 18번째 열 삭제
highest_sil: 0.2503162975078499
11, 19번째 열 삭제
highest_sil: 0.23832427022374517
11, 20번째 열 삭제
highest_sil: 0.2285898859774639
11, 21번째 열 삭제
highest_sil: 0.2285898859774639
11, 22번째 열 삭제
highest_sil: 0.2285898859774639
11, 23번째 열 삭제
highest_sil: 0.20003890256300141
12, 0번째 열 삭제
highest_sil: 0.23388210803667886
12, 1번째 열 삭제
highest_sil: 0.22803011037723056
12, 2번째 열 삭제
highest_sil: 0.2256345467000451
12, 3번째 열 삭제
highest_sil: 0.22347745983119044
12, 4번째 열 삭제
highest_sil: 0.22965217639145077
12, 5번째 열 삭제
highest_sil: 0.23555770775684404
12, 6번째 열 삭제
highest_sil: 0.18681143522594443
12, 7번째 열 삭제
highest_sil: 0.2231185604738954
12, 8번째 열 삭제
highest_sil: 0.22422423886471798
12, 9번째 열 삭제
highest_sil: 0.22872657227043303
12, 10번째 열 삭제
highest_sil: 0.22405720664890777
12, 11번째 열 삭제
highest_sil: 0.24568218381171916
12, 13번째 열 삭제
highest_sil: 0.22063184455694196
12, 14번째 열 삭제
highest_sil: 0.23218749818381768
12, 15번째 열 삭제
highest_sil: 0.234460591275171
12, 16번째 열 삭제
highest_sil: 0.22789274354726732
12, 17번째 열 삭제
highest_sil: 0.24104469998858954
12, 18번째 열 삭제
highest_sil: 0.22380492037620564
12, 19번째 열 삭제
highest_sil: 0.22197868091303258
12, 20번째 열 삭제
highest_sil: 0.22362985916265743
12, 21번째 열 삭제
highest_sil: 0.22362985916265743
12, 22번째 열 삭제
highest_sil: 0.22362985916265743
12, 23번째 열 삭제
highest_sil: 0.21544144142162688
13, 0번째 열 삭제
highest_sil: 0.2289426386074616
13, 1번째 열 삭제
highest_sil: 0.2076947455177156
13, 2번째 열 삭제
highest_sil: 0.22049537327905253
13, 3번째 열 삭제
highest_sil: 0.223204069088803
13, 4번째 열 삭제
highest_sil: 0.21057021182954253
13, 5번째 열 삭제
highest_sil: 0.21180519553958352
13, 6번째 열 삭제
highest_sil: 0.22206830177693146
13, 7번째 열 삭제
highest_sil: 0.2277917414939627
13, 8번째 열 삭제
highest_sil: 0.2232935678422237
13, 9번째 열 삭제
highest_sil: 0.20474005606102666
13, 10번째 열 삭제
highest_sil: 0.22658388744777275
13, 11번째 열 삭제
highest_sil: 0.23383059677683263
13, 12번째 열 삭제
highest_sil: 0.22063184455694196
13, 14번째 열 삭제
highest_sil: 0.21547231122380894
13, 15번째 열 삭제
highest_sil: 0.23629884209675925
13, 16번째 열 삭제
highest_sil: 0.21592966321992765
13, 17번째 열 삭제
highest_sil: 0.2317704033104721
13, 18번째 열 삭제
highest_sil: 0.22377293377345378
13, 19번째 열 삭제
highest_sil: 0.22163098652230698
13, 20번째 열 삭제
highest_sil: 0.22072473910893664
13, 21번째 열 삭제
highest_sil: 0.22072473910893664
13, 22번째 열 삭제
highest_sil: 0.22072473910893664
13, 23번째 열 삭제
highest_sil: 0.21065212467504854
14, 0번째 열 삭제
highest_sil: 0.21824733872447802
14, 1번째 열 삭제
highest_sil: 0.21158180645672187
14, 2번째 열 삭제
highest_sil: 0.2135809411758533
14, 3번째 열 삭제
highest_sil: 0.21331644253899285
14, 4번째 열 삭제
highest_sil: 0.22070502995856014
14, 5번째 열 삭제
highest_sil: 0.22797166535650043
14, 6번째 열 삭제
highest_sil: 0.23653519570748846
14, 7번째 열 삭제
highest_sil: 0.2117161877847871
14, 8번째 열 삭제
highest_sil: 0.2147481673167855
14, 9번째 열 삭제
highest_sil: 0.21171986689988964
14, 10번째 열 삭제
highest_sil: 0.21507908212377894
14, 11번째 열 삭제
highest_sil: 0.23811463116266737
14, 12번째 열 삭제
highest_sil: 0.23218749818381768
14, 13번째 열 삭제
highest_sil: 0.21547231122380894
14, 15번째 열 삭제
highest_sil: 0.2402051038983788
14, 16번째 열 삭제
highest_sil: 0.19354388144221787
14, 17번째 열 삭제
highest_sil: 0.23305033889129217
14, 18번째 열 삭제
highest_sil: 0.22729061985435123
14, 19번째 열 삭제
highest_sil: 0.2047941666115101
14, 20번째 열 삭제
highest_sil: 0.20625618292813705
14, 21번째 열 삭제
highest_sil: 0.20625618292813705
14, 22번째 열 삭제
highest_sil: 0.20625618292813705
14, 23번째 열 삭제
highest_sil: 0.20229258782429133
15, 0번째 열 삭제
highest_sil: 0.24219422205773902
15, 1번째 열 삭제
highest_sil: 0.2350001555608316
15, 2번째 열 삭제
highest_sil: 0.23207361215771768
15, 3번째 열 삭제
highest_sil: 0.22820397568806286
15, 4번째 열 삭제
highest_sil: 0.2226330805496583
15, 5번째 열 삭제
highest_sil: 0.24126095621024
15, 6번째 열 삭제
highest_sil: 0.23734205171983017
15, 7번째 열 삭제
highest_sil: 0.22802952036444774
15, 8번째 열 삭제
highest_sil: 0.22701426427552432
15, 9번째 열 삭제
highest_sil: 0.2306533123669225
15, 10번째 열 삭제
highest_sil: 0.21435547823897647
15, 11번째 열 삭제
highest_sil: 0.25490704358401156
15, 12번째 열 삭제
highest_sil: 0.234460591275171
15, 13번째 열 삭제
highest_sil: 0.23629884209675925
15, 14번째 열 삭제
highest_sil: 0.2402051038983788
15, 16번째 열 삭제
highest_sil: 0.21200071047266605
15, 17번째 열 삭제
highest_sil: 0.24753606459882238
15, 18번째 열 삭제
highest_sil: 0.22985178364835127
15, 19번째 열 삭제
highest_sil: 0.2263994599819129
15, 20번째 열 삭제
highest_sil: 0.21575408889239717
15, 21번째 열 삭제
highest_sil: 0.21575408889239717
15, 22번째 열 삭제
highest_sil: 0.21575408889239717
15, 23번째 열 삭제
highest_sil: 0.22045978023773
16, 0번째 열 삭제
highest_sil: 0.21907766178898377
16, 1번째 열 삭제
highest_sil: 0.21522814995943368
16, 2번째 열 삭제
highest_sil: 0.2043429121954855
16, 3번째 열 삭제
highest_sil: 0.20105856728341373
16, 4번째 열 삭제
highest_sil: 0.21431502018315987
16, 5번째 열 삭제
highest_sil: 0.20194674570026758
16, 6번째 열 삭제
highest_sil: 0.22946026144236398
16, 7번째 열 삭제
highest_sil: 0.2053250553498559
16, 8번째 열 삭제
highest_sil: 0.21964855480617476
16, 9번째 열 삭제
highest_sil: 0.2027575391919102
16, 10번째 열 삭제
highest_sil: 0.19371345710029575
16, 11번째 열 삭제
highest_sil: 0.23666840874608136
16, 12번째 열 삭제
highest_sil: 0.22789274354726732
16, 13번째 열 삭제
highest_sil: 0.21592966321992765
16, 14번째 열 삭제
highest_sil: 0.19354388144221787
16, 15번째 열 삭제
highest_sil: 0.21200071047266605
16, 17번째 열 삭제
highest_sil: 0.22572032533569242
16, 18번째 열 삭제
highest_sil: 0.22021466976581489
16, 19번째 열 삭제
highest_sil: 0.21866287043395394
16, 20번째 열 삭제
highest_sil: 0.20815257312628763
16, 21번째 열 삭제
highest_sil: 0.20815257312628763
16, 22번째 열 삭제
highest_sil: 0.20815257312628763
16, 23번째 열 삭제
highest_sil: 0.20741836438183456
17, 0번째 열 삭제
highest_sil: 0.23356255340938223
17, 1번째 열 삭제
highest_sil: 0.22715370547378305
17, 2번째 열 삭제
highest_sil: 0.1999640185848522
17, 3번째 열 삭제
highest_sil: 0.2201576235242585
17, 4번째 열 삭제
highest_sil: 0.23203811073635572
17, 5번째 열 삭제
highest_sil: 0.2347848210521577
17, 6번째 열 삭제
highest_sil: 0.2445675740793973
17, 7번째 열 삭제
highest_sil: 0.231221704330906
17, 8번째 열 삭제
highest_sil: 0.23202110015393002
17, 9번째 열 삭제
highest_sil: 0.23423212162484416
17, 10번째 열 삭제
highest_sil: 0.23727574436578183
17, 11번째 열 삭제
highest_sil: 0.2545391714282018
17, 12번째 열 삭제
highest_sil: 0.24104469998858954
17, 13번째 열 삭제
highest_sil: 0.2317704033104721
17, 14번째 열 삭제
highest_sil: 0.23305033889129217
17, 15번째 열 삭제
highest_sil: 0.24753606459882238
17, 16번째 열 삭제
highest_sil: 0.22572032533569242
17, 18번째 열 삭제
highest_sil: 0.23383431566063714
17, 19번째 열 삭제
highest_sil: 0.2130803302274685
17, 20번째 열 삭제
highest_sil: 0.22273352732724905
17, 21번째 열 삭제
highest_sil: 0.22273352732724905
17, 22번째 열 삭제
highest_sil: 0.22273352732724905
17, 23번째 열 삭제
highest_sil: 0.2245105260919264
18, 0번째 열 삭제
highest_sil: 0.21130525469559525
18, 1번째 열 삭제
highest_sil: 0.2225727298192605
18, 2번째 열 삭제
highest_sil: 0.1997021816684386
18, 3번째 열 삭제
highest_sil: 0.22782740874660148
18, 4번째 열 삭제
highest_sil: 0.22029588916091494
18, 5번째 열 삭제
highest_sil: 0.21704069258728126
18, 6번째 열 삭제
highest_sil: 0.23485281510922393
18, 7번째 열 삭제
highest_sil: 0.22568784864766112
18, 8번째 열 삭제
highest_sil: 0.20549382935097496
18, 9번째 열 삭제
highest_sil: 0.21274255452758403
18, 10번째 열 삭제
highest_sil: 0.205918552143757
18, 11번째 열 삭제
highest_sil: 0.2503162975078499
18, 12번째 열 삭제
highest_sil: 0.22380492037620564
18, 13번째 열 삭제
highest_sil: 0.22377293377345378
18, 14번째 열 삭제
highest_sil: 0.22729061985435123
18, 15번째 열 삭제
highest_sil: 0.22985178364835127
18, 16번째 열 삭제
highest_sil: 0.22021466976581489
18, 17번째 열 삭제
highest_sil: 0.23383431566063714
18, 19번째 열 삭제
highest_sil: 0.22563508599616083
18, 20번째 열 삭제
highest_sil: 0.20959259625550503
18, 21번째 열 삭제
highest_sil: 0.20959259625550503
18, 22번째 열 삭제
highest_sil: 0.20959259625550503
18, 23번째 열 삭제
highest_sil: 0.21127434542864473
19, 0번째 열 삭제

In [ ]:
K_range = range(2,14)

#열 4개 삭제
for l in range(0,24):
for k in range(0,24): 
    range_without_k = [x for x in range(24) if x != k]
    for j in range(0,24):
        range_without_j = [x for x in range(24) if x != j]
        for i in range_without_j:
            print(f"{j}, {i}번째 열 삭제")
            declined_columns_df = df.drop([df.columns[i], df.columns[j], df.columns[k]], axis=1)

            highest_sil=0
        
            for n_clusters in K_range:
                kmeans = KMeans(n_clusters=n_clusters, random_state=42)
       
                cluster_labels = kmeans.fit_predict(declined_columns_df)
        
                if (silhouette_score(declined_columns_df, cluster_labels) > highest_sil):
                    highest_sil = silhouette_score(declined_columns_df, cluster_labels)
            
            print(f"highest_sil: {highest_sil}")

In [ ]:
inertia_kmeans = []
sil_scores_kmeans = []
K_range = range(2,14)

for n_clusters in K_range:
    kmeans = KMeans(n_clusters=n_clusters, random_state=42, n_init=10)
    # n_init: initial centroid 변경횟수 
    # 없이 했다가 추가하니까 실루엣스코어 살짝씩 올랐음
    cluster_labels = kmeans.fit_predict(df)
    
    inertia_kmeans.append(kmeans.inertia_)
    sil_scores_kmeans.append(silhouette_score(df, cluster_labels))